---
# tasks file for nginx

- name: Ensure nginx container has an up-to-date configuration
  docker:
    name: "{{ nginx_container_name }}"
    image: "nginx:{{ nginx_version }}" # use official docker image library
    state: "reloaded"
    pull: always
    ports:
      - "{{ nginx_port }}:80"
      - "{{ nginx_https_port }}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "{{ nginx_certs_path }}:/etc/nginx/certs"
      - "{{ nginx_htpasswd_path }}:/etc/nginx/htpasswd"
      - "{{ nginx_config_path }}/proxy.conf:/etc/nginx/proxy.conf"

  tags:
    - docker
